kubeProxyReplacement: true

# Spoke (dev/staging/prod): bật clustermesh-apiserver để management có endpoint remote thật
# (NodePort trên mỗi spoke) trong mô hình GitOps declarative.
clustermesh:
  useAPIServer: true
  apiserver:
    replicas: 1
tls:
  ca:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIDEzCCAfugAwIBAgIQLLaCJtpDspDBMBX1/gpMDTANBgkqhkiG9w0BAQsFADAU
      MRIwEAYDVQQDEwlDaWxpdW0gQ0EwHhcNMjYwNDI0MDMxOTQ1WhcNMjkwNDIzMDMx
      OTQ1WjAUMRIwEAYDVQQDEwlDaWxpdW0gQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      DwAwggEKAoIBAQC/o3TgrUJT3XHjVvz+0CNlBalSMPmS+L4pBMItgnuCoecp3ohN
      QoJV1s/QsXv12NldVzZXhZnvJYeC/0p82fmof7BucUtQ9fTOuMZQYCTUZ09WG+eD
      cVHVKkON6SlkAIH39C0BVRoKy3SMqw5pQWQoEx2A5Jr0ylmJ5Lc6kFCa0ssbxoIe
      rBgCiG9wABeuI3/Xr5utaRdp0vhqRuyFbypF0wix7pSKUFtM8jR6jXKtVskqbneg
      C3wSfgL9F+puuMNRdtpLOk88nf1huBT6Ra4AGed5MZrriFcZDUUsgI/rCeEsvw4d
      79BmFqH3+dSgf4ZxhQwkNaPXq0coo6l5Rk/7AgMBAAGjYTBfMA4GA1UdDwEB/wQE
      AwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUw
      AwEB/zAdBgNVHQ4EFgQUkQlMJqmnpsF12H2FWNHLznCRhoQwDQYJKoZIhvcNAQEL
      BQADggEBAK7oi0oRftVvQwdnmbhWDu+6qH7zI+/PSaGRgVRP8WxihWKIGHlW9gKk
      YrCon/NhVY7ANxAk2HVgrEFnwp8oGlP9UpJJsrGgGMP+Plx51SY10HEAQME+OCe1
      bE02EYjupUujP3yrqDecGqTXtrDp4g632YVQFCGE++/JqskxUbA12lBNEgZWyuxE
      X+HFRqeW5Ye4Ft6tJfUxUN5fcKSpdOqx9fqQ1d1vhuSRSfi6QTtgrktGw6YsVzbU
      Gti6nArzaIVncf1oTzoLOMMjekjmmc2oMYrpMlOxEieQjkF0cGHAtY2wuBN4d4sB
      dFroBkKP1AznRZos+oOdpmiep3jiwHE=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAv6N04K1CU91x41b8/tAjZQWpUjD5kvi+KQTCLYJ7gqHnKd6I
      TUKCVdbP0LF79djZXVc2V4WZ7yWHgv9KfNn5qH+wbnFLUPX0zrjGUGAk1GdPVhvn
      g3FR1SpDjekpZACB9/QtAVUaCst0jKsOaUFkKBMdgOSa9MpZieS3OpBQmtLLG8aC
      HqwYAohvcAAXriN/16+brWkXadL4akbshW8qRdMIse6UilBbTPI0eo1yrVbJKm53
      oAt8En4C/RfqbrjDUXbaSzpPPJ39YbgU+kWuABnneTGa64hXGQ1FLICP6wnhLL8O
      He/QZhah9/nUoH+GcYUMJDWj16tHKKOpeUZP+wIDAQABAoIBAFI/lbieM+Lpnmkb
      mw7EBwTjFqY7dcoB7x+MtsgwgdDxqtR5+VbrbiPoQ54GprS/wp7AgQa0RPpySYRM
      DEykgvWyA+eKwW/4d/7HJ/o0IWp2AoNrC4SK/Lu33XGJOiX838srJau2Oiya4KVE
      /zTmh1V5ysZYlzbrp906Z/d/G9EuXDMsiSVU/SMIBTuLLaf8BIsPlmhV9Svv4FvT
      eYMpLNU4BBuDRQdQlfBqkMOcSKK2f+EKf1G/1A5PR1Yds0LFnRYqjZuAAVQq2Rk2
      Q3gaxMM3YLns/sp/d5J8xsvjAytTC0LKtgMTpeaMZrLP/ASCNPXfXRMj+cgZiXs4
      srzkHqkCgYEA3xTLKSM1M3yynLAyX96SBtF2rBB+YjfDtDR5td4weRrwn/VD18BG
      Uf1BccnoxxLN9zfT6JzJL+67RXrMXDw1qW8fcg2PWggcWxCmOT5e/8+HYBdEf3hD
      hhfaCtKM+SvBynW/qRULnpJY7n4CgACk7JRGziOqLGoV7ROCNaEjsRkCgYEA2+re
      ti1qkv39nLoqg6Ku3GgOjjgsrL3FO5yuUyO1pchZbg1MJ7rktrYeI8AcVDPrWeZQ
      O7SLR2RdMcj3n5OjlK6y4OJaMFuw310mCgCRsCa22mTM2+P/HyiwHpcwBGXgYJoC
      iCnfmmoJ/KQH/Nm3+ZjC2tVFi62Skhcc90STSDMCgYEAovqGEt/uFlecBm2T4Aaz
      mNefY8YJD6i+CgHsibpyn4fXFIYTsqR+u5fTIFbrAcXzRBI9d0xUj/hSSUiV1S0H
      52mQB7twZ85VKRLY3il7LlloBgP5v0cVzfnPCukYpVIamte71sPRYWB6KINXQD04
      QL9zm1bjFN/MdRAzqQq5EMECgYA4npKyYqUCrUPjWwbhFzxf4KaGtS3DV6R1AZTc
      MOBui1ODAwdtXy/NXrwJxkdE4o0geyyDAqutOMjJrY0bV56RBB1nyr8fniu+hjPp
      9VWM/ZqsRbF8l4mykv4tEg25xCTtmhk2x1kbX1us4OpxjfhQ2aSpRKmAGbMXy72Y
      Z95ngwKBgC9A/qrDQB8CUABq/vHwJBOazDjfUgPv0rJSJJDy6tz7P2c1LheFeBbI
      FgrHaG+vnaGbxxlwiP/GMJX4gR3uE+RkLkSZ9rxQB8Dv9FZbNTb2lAklzD49+o3H
      gDyg67xf5SSpuJ5QThrPzQFee/ZpC7eNabaVqOxA0pqC0hTUpfAf
      -----END RSA PRIVATE KEY-----
