projectName: go-micro
secretStoreName: aws-secrets-manager
region: ap-southeast-1

product:
  namespace: microservices
  syncWave: "-2"
  secrets:
    refreshInterval: 1h
    data:
      - secretKey: DB_USER
        remoteRef:
          property: DB_USER
      - secretKey: DB_PASSWORD
        remoteRef:
          property: DB_PASSWORD
      - secretKey: DB_NAME
        remoteRef:
          property: PRODUCT_DB_NAME

inventory:
  namespace: microservices
  syncWave: "-2"
  secrets:
    refreshInterval: 1h
    data:
      - secretKey: DB_USER
        remoteRef:
          property: DB_USER
      - secretKey: DB_PASSWORD
        remoteRef:
          property: DB_PASSWORD
      - secretKey: DB_NAME
        remoteRef:
          property: INVENTORY_DB_NAME

order:
  namespace: microservices
  syncWave: "-2"
  secrets:
    refreshInterval: 1h
    data:
      - secretKey: DB_USER
        remoteRef:
          property: DB_USER
      - secretKey: DB_PASSWORD
        remoteRef:
          property: DB_PASSWORD
      - secretKey: DB_NAME
        remoteRef:
          property: ORDER_DB_NAME

noti:
  namespace: microservices
  syncWave: "-2"
  secrets:
    refreshInterval: 1h
    data:
      - secretKey: DB_USER
        remoteRef:
          property: DB_USER
      - secretKey: DB_PASSWORD
        remoteRef:
          property: DB_PASSWORD
      - secretKey: DB_NAME
        remoteRef:
          property: NOTIFICATION_DB_NAME

payment:
  namespace: microservices
  syncWave: "-2"
  secrets:
    refreshInterval: 1h
    data:
      - secretKey: DB_USER
        remoteRef:
          property: DB_USER
      - secretKey: DB_PASSWORD
        remoteRef:
          property: DB_PASSWORD
      - secretKey: DB_NAME
        remoteRef:
          property: PAYMENT_DB_NAME
