apiVersion: v2
name: go-micro
description: A Helm chart for Go Microservices E-commerce Application

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Databases
  - name: product-db
    version: "0.1.0"
    repository: "file://./charts/product-db"
  - name: inventory-db
    version: "0.1.0"
    repository: "file://./charts/inventory-db"
  - name: order-db
    version: "0.1.0"
    repository: "file://./charts/order-db"
  - name: payment-db
    version: "0.1.0"
    repository: "file://./charts/payment-db"
  - name: notification-db
    version: "0.1.0"
    repository: "file://./charts/notification-db"
  
  # Message Queue & Cache
  - name: rabbitmq
    version: "0.1.0"
    repository: "file://./charts/rabbitmq"
  - name: redis
    version: "0.1.0"
    repository: "file://./charts/redis"
  
  # Microservices
  - name: product-service
    version: "0.1.0"
    repository: "file://./charts/product-service"
  - name: inventory-service
    version: "0.1.0"
    repository: "file://./charts/inventory-service"
  - name: order-service
    version: "0.1.0"
    repository: "file://./charts/order-service"
  - name: payment-service
    version: "0.1.0"
    repository: "file://./charts/payment-service"
  - name: noti-service
    version: "0.1.0"
    repository: "file://./charts/noti-service"
  
  # API Gateway & Frontend
  - name: api-gateway
    version: "0.1.0"
    repository: "file://./charts/api-gateway"
  - name: client
    version: "0.1.0"
    repository: "file://./charts/client"
