apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: {{ .Values.inventoryService.database.password | quote }}