# api-gateway/templates/ingress.yaml
{{- if and .Values.ingress.enabled (not .Values.httpRoute.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Values.app.namespace | default .Release.Namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ include "api-gateway.fullname" . }}
                  port: 
                    name: http # Reference the service port by its name
{{- end }}