global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8081']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8082']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8084']
