apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "product-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.productService.name }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_DEFAULT_REGION
          image: "{{ .Values.workload.image }}:{{ .Values.workload.tag }}"
          imagePullPolicy: {{ .Values.workload.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.workload.ports.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /products
              port: {{ .Values.workload.ports.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /products
              port: {{ .Values.workload.ports.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ include "product-service.fullname" . }}-configmap
            - secretRef:
                name: {{ include "product-service.fullname" . }}-secret
          resources:
            {{- toYaml .Values.workload.resources | nindent 12 }}
