apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
  
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: {{ .Values.productService.database.password | quote }}
