replicaCount: 2

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: external-gateway
      namespace: istio-ingress

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


orderService:
  name: order-service-deployment
  namespace: go-micro
  database:
    host: "order-db"
    port: "5432"
    name: "order_db"
    user: "postgres"
  redis:
    host: "redis"
    port: "6379"
  rabbitmq:
    host: "rabbitmq"
    port: "5672"

workload:
  image: 398045402467.dkr.ecr.ap-southeast-2.amazonaws.com/order-service
  tag: "latest" # Using ECR image
  resources:
    requests:
      memory: 256Mi
      cpu: 128m
    limits:
      memory: 512Mi
      cpu: 500m
  ports:
    containerPort: 8081

service:
  type: ClusterIP
  port: 8083
  targetPort: 8081

ingress:
  enabled: false

serviceAccount:
  create: false

imagePullSecrets:
  - name: ecr-secret
