apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.orderService.database.host | default "order-db" | quote }}
  DB_PORT: {{ .Values.orderService.database.port | default "5432" | quote }}
  DB_NAME: {{ .Values.orderService.database.name | default "order_db" | quote }}
  DB_USER: {{ .Values.orderService.database.user | default "postgres" | quote }}
  DB_PASSWORD: {{ .Values.orderService.database.password | default "canh177" | quote }}
  REDIS_HOST: {{ .Values.orderService.redis.host | default "go-micro-redis" | quote }}
  REDIS_PORT: {{ .Values.orderService.redis.port | default "6379" | quote }}
  RABBITMQ_HOST: {{ .Values.orderService.rabbitmq.host | default "go-micro-rabbitmq" | quote }}
  RABBITMQ_PORT: {{ .Values.orderService.rabbitmq.port | default "5672" | quote }}
  RABBITMQ_USER: {{ .Values.orderService.rabbitmq.user | default "guest" | quote }}
  RABBITMQ_PASS: {{ .Values.orderService.rabbitmq.password | default "guest" | quote }}
  INVENTORY_SERVICE_URL: {{ .Values.orderService.inventoryServiceUrl | default "http://go-micro-inventory-service" | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.orderService.productServiceUrl | default "http://go-micro-product-service" | quote }}
  PAYMENT_SERVICE_URL: {{ .Values.orderService.paymentServiceUrl | default "http://go-micro-payment-service" | quote }}
  NOTIFICATION_SERVICE_URL: {{ .Values.orderService.notificationServiceUrl | default "http://go-micro-noti-service" | quote }}