nameOverride: ""
fullnameOverride: "payment-db"

image:
  repository: postgres
  tag: "14-alpine"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5432

serviceAccount:
  create: false
  name: ""

auth:
  username: "postgres"
  password: "canh177"
  database: "payment_db"
  hostAuthMethod: "md5"

persistence:
  enabled: true
  size: 1Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1