replicaCount: 2

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: external-gateway
      namespace: istio-ingress

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


productService:
  name: product-service-deployment
  namespace: go-micro
  stripe:
    secretKey: ""
  database:
    password: "canh177"

workload:
  image: 675613596870.dkr.ecr.ap-southeast-2.amazonaws.com/product-service
  tag: "latest" # Using ECR image
  resources:
    requests:
      memory: 256Mi
      cpu: 128m
    limits:
      memory: 512Mi
      cpu: 500m
  ports:
    containerPort: 8080
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

serviceAccount:
  create: false

imagePullSecrets:
  - name: ecr-secret
