apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noti-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "noti-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "noti-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "noti-service.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.workload.ports.containerPort }}"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: {{ .Values.notiService.name }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_DEFAULT_REGION
          image: "{{ .Values.workload.image }}:{{ .Values.workload.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.workload.ports.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.workload.ports.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.workload.ports.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ include "noti-service.fullname" . }}-configmap
            - secretRef:
                name: {{ include "noti-service.fullname" . }}-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "500m"
