apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "payment-db.selectorLabels" . | nindent 4 }}