env: prod
projectName: go-micro

product:
  secrets:
    target:
      name: go-micro-product-secrets
    remoteKey: go-micro/prod/app-credentials

inventory:
  secrets:
    target:
      name: go-micro-inventory-secrets
    remoteKey: go-micro/prod/app-credentials

order:
  secrets:
    target:
      name: go-micro-order-secrets
    remoteKey: go-micro/prod/app-credentials

noti:
  secrets:
    target:
      name: go-micro-noti-secrets
    remoteKey: go-micro/prod/app-credentials

payment:
  secrets:
    target:
      name: go-micro-payment-secrets
    remoteKey: go-micro/prod/app-credentials
