env: staging
projectName: go-micro

routing:
  provider: traefik

traefik:
  enabled: true
  hostname: staging.go-micro.local
  stableWeight: 90
  canaryWeight: 10

ciliumNetworkPolicy:
  enabled: false
  authenticationMode: ""

rollout:
  enabled: false
  analysis:
    enabled: true
    prometheusAddress: http://172.18.0.3:32090
    templates:
      - name: success-rate
        args:
          - name: service-name
        metrics:
          - name: success-rate
            interval: 30s
            count: 5
            initialDelay: 45s
            failureLimit: 3
            successCondition: result[0] >= 0.82
            failureCondition: result[0] < 0.82
            provider:
              prometheus:
                address: '{{ .Values.rollout.analysis.prometheusAddress | default "http://172.18.0.3:32090" }}'
                query: |
                  avg(up{namespace="{{ .Release.Namespace }}",pod=~"{{ "{{" }}args.service-name{{ "}}" }}-.*"}) or vector(0)
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - analysis:
          templates:
            - templateName: '{{ include "template.fullname" . }}-success-rate'
          args:
            - name: service-name
              value: '{{ include "template.fullname" . }}'
      - setWeight: 50
      - setWeight: 100
  blueGreen:
    activeService: ""
    previewService: ""
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 30

product:
  namespace: microservices-staging
  secrets:
    target:
      name: go-micro-product-secrets-staging
    remoteKey: go-micro/staging/app-credentials

inventory:
  namespace: microservices-staging
  secrets:
    target:
      name: go-micro-inventory-secrets-staging
    remoteKey: go-micro/staging/app-credentials

order:
  namespace: microservices-staging
  secrets:
    target:
      name: go-micro-order-secrets-staging
    remoteKey: go-micro/staging/app-credentials

noti:
  namespace: microservices-staging
  secrets:
    target:
      name: go-micro-noti-secrets-staging
    remoteKey: go-micro/staging/app-credentials

payment:
  namespace: microservices-staging
  secrets:
    target:
      name: go-micro-payment-secrets-staging
    remoteKey: go-micro/staging/app-credentials
