apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-micro-inventory-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minhtri1612/go-micro.git
    targetRevision: HEAD
    path: main/charts/inventory-db
    helm:
      releaseName: go-micro
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: go-micro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true

