replicaCount: 2

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: external-gateway
      namespace: istio-ingress

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


notiService:
  name: noti-service-deployment
  namespace: go-micro

workload:
  image: 675613596870.dkr.ecr.ap-southeast-2.amazonaws.com/notification-service
  tag: "latest" # Using ECR image
  resources:
    requests:
      memory: 256Mi
      cpu: 128m
    limits:
      memory: 512Mi
      cpu: 500m
  ports:
    containerPort: 8083

service:
  type: ClusterIP
  port: 80
  targetPort: 8083

ingress:
  enabled: false

serviceAccount:
  create: false

imagePullSecrets:
  - name: ecr-secret
