replicaCount: 2

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: external-gateway
      namespace: istio-ingress

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


notiService:
  name: noti-service-deployment
  namespace: go-microservice

workload:
  image: 675613596870.dkr.ecr.ap-southeast-2.amazonaws.com/notification-service
  tag: "latest" # It's better to override this with a specific tag during deployment
  resources:
    requests:
      memory: "256Mi"
      cpu: "128m"
    limits:
      memory: "2Gi"
      cpu: "1" # "1000m" is equivalent to "1" CPU core
  ports:
    containerPort: 8083

service:
  type: ClusterIP
  port: 80
  targetPort: 8083

ingress:
  enabled: false

serviceAccount:
  create: false
