apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}
  namespace: {{ .Values.app.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "client.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "client.name" . }}