apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: {{ .Values.paymentService.database.password | quote }}
  STRIPE_SECRET_KEY: {{ .Values.paymentService.stripe.secretKey | quote }}