replicaCount: 2 # Matches noti-service replica count

httpRoute:
  enabled: false # Disable HTTPRoute because Gateway API CRDs are not installed
  annotations: {}
  parentRefs:
    - name: external-gateway # Assuming this is your central Istio/Envoy gateway
      namespace: istio-ingress

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

app:
  namespace: go-micro # Assuming deployment in the same namespace

# Container and Resource Configuration
workload:
  # IMPORTANT: Replace with your actual ECR path for the API Gateway image
  image: 398045402467.dkr.ecr.ap-southeast-2.amazonaws.com/client
  tag: "latest" 
  resources:
    requests:
      memory: 256Mi
      cpu: 128m
    limits:
      memory: 512Mi
      cpu: 500m
  ports:
    containerPort: 80 # The port EXPOSEd in your API Gateway Dockerfile

env:
  # This MUST be the public URL of your API Gateway LoadBalancer
  VITE_API_URL: ""

service:
  type: LoadBalancer # Use LoadBalancer instead of ALB ingress
  port: 80 # Service port 
  targetPort: 80  # Must match workload.ports.containerPort

ingress:
  enabled: false # Disable ingress, use LoadBalancer service instead

serviceAccount:
  create: false

imagePullSecrets:
  - name: ecr-secret
