apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "notification-db.selectorLabels" . | nindent 4 }}