env: prod

backend:
  image:
    tag: "api-gateway-v1.0.1"
  version: "v1.0.1"
  replicaCount: 3

database:
  image:
    tag: "15-alpine"
  version: "15-alpine"
  replicaCount: 1

# Service-specific overrides
api-gateway:
  image:
    tag: "api-gateway-v1.0.1"
  replicaCount: 3

product:
  image:
    tag: "product-service-v1.0.1"
  replicaCount: 3

inventory:
  image:
    tag: "inventory-service-v1.0.1"
  replicaCount: 3

order:
  image:
    tag: "order-service-v1.0.1"
  replicaCount: 5

payment:
  image:
    tag: "payment-service-v1.0.1"
  replicaCount: 5

noti:
  image:
    tag: "notification-service-v1.0.1"
  replicaCount: 3

client:
  image:
    tag: "client-v1.0.1"
  replicaCount: 3

# Database services
product-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

inventory-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

order-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

payment-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

notification-db:
  image:
    tag: "15-alpine"
  replicaCount: 1
