env: prod

# Service-specific overrides

product:
  image:
    tag: "product-service-v1.0.2"
  replicaCount: 3
  rollout:
    enabled: true
    strategy: bluegreen

inventory:
  image:
    tag: "inventory-service-v1.0.2"
  replicaCount: 3
  rollout:
    enabled: true
    strategy: bluegreen

order:
  image:
    tag: "order-service-v1.0.2"
  replicaCount: 5
  rollout:
    enabled: true
    strategy: bluegreen

payment:
  image:
    tag: "payment-service-v1.0.2"
  replicaCount: 5
  rollout:
    enabled: true
    strategy: bluegreen

noti:
  image:
    tag: "notification-service-v1.0.2"
  replicaCount: 3
  rollout:
    enabled: true
    strategy: bluegreen

client:
  image:
    tag: "client-v1.0.2"
  replicaCount: 3
  rollout:
    enabled: true
    strategy: bluegreen

# Database services
product-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

inventory-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

order-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

payment-db:
  image:
    tag: "15-alpine"
  replicaCount: 1

notification-db:
  image:
    tag: "15-alpine"
  replicaCount: 1
