ount: 3aC"
  replicv1.0.1lient-: "c tag   ge:
ient:
  ima 2

cleplicaCount:1"
  rvice-v1.0.-sertion "notifica:
    tag:ti:
  image
no3
plicaCount: 0.1"
  reervice-v1.ment-sg: "payta
    :gema
  iment:t: 5

pay replicaCoun
 e-v1.0.1"rder-servic "o:
    tag:
  image: 3

ordert:eplicaCoun"
  r0.1ervice-v1.ntory-sg: "inve
    ta:
  image:oryent

inv 3aCount:plic"
  revice-v1.0.1duct-serg: "proge:
    ta ima
product:
 3
nt: eplicaCou.1"
  rateway-v1.0pi-g "ag:   tage:
 ma  iateway:
rides
api-g overce-specific

# Serviunt: 1eplicaCone"
  r"15-alpision:  veralpine"
 ag: "15-  t image:
  e:
 atabas3

dt: un  replicaCo"
.1n: "v1.0sio ver
 .0.1"gateway-v1api-ag: "age:
    t:
  imndckerod

baenv: p